import { NextResponse } from "next/server";
import { cookies } from "next/headers";
import { createServerClient } from "@supabase/ssr";
import { runRevenueAnalysis } from "@/lib/revenue-engine";
import { supabaseAdmin } from "@/lib/supabase-admin";

const ALLOWED_ROLES = [
  "admin", "super_admin", "revenue_manager", "finance_manager", "operations_manager", "branch_manager", "viewer"
];

async function verifyStaffAccess() {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() { return cookieStore.getAll(); },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options));
        },
      },
    }
  );

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: profile } = await supabase
    .from("users")
    .select(`*, role:roles (name)`)
    .eq("auth_user_id", user.id)
    .single();

  if (!profile) return null;
  const roleName = (profile.role as { name: string } | null)?.name || "";
  
  if (ALLOWED_ROLES.includes(roleName)) {
    return profile;
  }
  return null;
}

export async function GET(req: Request) {
  const profile = await verifyStaffAccess();
  if (!profile) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { searchParams } = new URL(req.url);
  const type = searchParams.get("type") || "daily";

  try {
    const analysis = await runRevenueAnalysis();

    // Check if we already have saved reports in executive_reports table
    // (We wrap in try-catch to support fallback if SQL setup is not yet run in Supabase)
    let savedReport = null;
    try {
      const { data } = await supabaseAdmin
        .from("executive_reports")
        .select("*")
        .eq("report_type", type)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      savedReport = data;
    } catch {
      // Setup not run yet
    }

    if (savedReport) {
      return NextResponse.json({ report: savedReport.report_data, source: "database" });
    }

    // Otherwise compile a fresh response summary
    const reportData = {
      timestamp: new Date().toISOString(),
      reportType: type,
      kpis: {
        totalRevenue: analysis.financials.expectedRevenue,
        lostRevenue: analysis.financials.lostRevenue,
        opportunityRevenue: analysis.financials.opportunityRevenue,
        occupancy: 74, // Estimated default occupancy
        utilization: 68,
      },
      forecast: analysis.forecast,
      topRecommendedActions: analysis.recommendations,
      summary: `Automated ${type} intelligence summary generated by AI Revenue Manager. Fleet operations have achieved optimal output, but minor leakages are recorded in unpaid bookings.`
    };

    return NextResponse.json({ report: reportData, source: "generated" });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
